FROM ubuntu:18.04

ARG ARCH

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    tar \
    gzip \
    gcc-aarch64-linux-gnu

WORKDIR /work
COPY . .

RUN make clean && \
    if [ "$ARCH" = "arm64" ]; then \
        make CC=aarch64-linux-gnu-gcc; \
    else \
        make;
    fi
