FROM almalinux:8

ARG ARCH

RUN dnf install -y gcc gcc-c++ make git tar gzip \
    gcc-aarch64-linux-gnu

WORKDIR /work
COPY . .

RUN make clean && \
    if [ "$ARCH" = "arm64" ]; then \
      make CC=aarch64-linux-gnu-gcc; \
    else \
      make; \
    fi
